# Generated by Django 4.1.4 on 2023-02-24 07:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_file_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_data',
            old_name='name',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='file_data',
            name='image',
        ),
        migrations.AddField(
            model_name='file_data',
            name='file',
            field=models.FileField(default=datetime.datetime(2023, 2, 24, 7, 47, 9, 974158, tzinfo=datetime.timezone.utc), upload_to='file_folder'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='image_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
